version: "3.8"
services:
  bot:
    container_name: jay-bot
    build: .
    ports:
      - 8080:8080
    # volumes:
    #   - .:.
    depends_on:
      - redis
    networks:
      - front-tier
      - back-tier
  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
    restart: always
    command: redis-server /usr/local/conf/redis.conf
    volumes:
      - redis-data:/var/lib/redis
      - ./conf/redis.conf:/usr/local/conf/redis.conf
    networks:
      - back-tier
volumes:
  redis-data:
    driver: local
networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge
